# -*- coding: utf-8 -*-
"""day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SyoNuj8kxxa1RgzMbQJ5BiGpyhfBE7lj
"""

def textToDigit(line):
  numbers = ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]
  final = line
  for n in numbers:
      if n in final:
        separate = final.split(n)
      else:
        continue
      separator = n + str(numbers.index(n) + 1) + n
      final = separator.join(separate) if len(separate) > 1 else separate

  return final

def digitCount(line):
  sum = 0
  for character in singleLine:
    if ord(character) in range(49, 58):
      sum = sum + 10*int(character)
      break
  for character in singleLine[::-1]:
    if ord(character) in range(49, 58):
      sum = sum + int(character)
      break
  return sum

wholeList = open("list.txt", "r").readlines()
sum = 0

for singleLine in wholeList:
  sum = sum + digitCount(singleLine)
print(sum)

sum = 0

for singleLine in wholeList:
  singleLine = textToDigit(singleLine)
  sum = sum + digitCount(singleLine)
print(sum)